language: go

sudo: false

go:
  - 1.4.3
  - 1.5.3
  - 1.6rc2
  - tip

env:
  - GOARCH=amd64

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - export PATH="$HOME/gopath/bin:$PATH"
  - go get github.com/tools/godep
  - go get -t -d ./...
  - godep restore ./...

script:
  - cd $HOME/gopath/src/github.com/albertoleal/features
  - $HOME/gopath/bin/goveralls -service=travis-ci
  - go test -x ./...

notifications:
  email:
    recipients:
      - albertonb@gmail.com

